### PR TITLE
Feature: Rounded frame corners

### PR DESCRIPTION
**Pull request by rduriancik**
Hi. Thank you for your awesome library. I have to round the frame corners because of the app's design. I implemented it as another attribute of the `CodeScannerView` and draw it on the canvas in the `ViewFinderView`. If you have any questions about the implementation or you need me to change something, feel free to ask. 

I had some issues with the mask because canvas.clipPath() doesn't support anti-aliasing, which made the round corners pixelated, so I decided to create it from the top and bottom part. The implementation of corners rounding is based on this answer https://stackoverflow.com/a/28655800 , but I had to adjust it to my needs.

### CODE REVIEW

**Comment by yuriy-budiyev** [comment]
Do we really need three Path objects? I maean why not just mFramePath and mMaskPath, or just one Path object for all drawnigs?

**Comment by rduriancik** [comment]
I think I can use only two paths. One for mask and the second one for frame. But I maybe it could work with one path. Let me try I few things. I'll let you know then.

**Comment by yuriy-budiyev** [comment]
Ok)

**Comment by rduriancik** [comment]
So, I was able to do it with two paths. I don't think I can make it just with one path because the mask between frame corners goes only to the half of the stroke width. Sry, first time I'm working with canvas and paths.
screenshot_2018-10-27-13-36-22
 size.

**Comment by rduriancik** [comment]
I think I can get rid off the frameStrokeWidth. I've had to use it because of the clipPath method but with this approach, it is not needed.

**Comment by yuriy-budiyev** [comment]
Ok. Thanks. But I can't release this right now, so I'll remove changes from readme file. And also, I think we can leave onle one radius setting, for all corners.

**Pull request merged**
