### PR TITLE
Inverted code scanning

### PR DESCRIPTION
**Pull request by x0rb0t**
White QrCodes on a black background are not scanned. Please check this code (it may not compile), did not test, but took it from 
https://github.com/dm77/barcodescanner/blob/master/zxing/src/main/java/me/dm7/barcodescanner/zxing/ZXingScannerView.java

### CODE REVIEW

**Comment by x0rb0t** [comment]
Надеюсь на быстрый фикс :)

**Comment by yuriy-budiyev** [comment]
Seems like we just need to add smgle method call. Thanks for the issue.

**Comment by yuriy-budiyev** [comment]
Fixed in 1.9.3

**Comment by x0rb0t** [comment]
I have uptaded and tested 1.9.3
It still does **not** work. 
Maybe reader.reset() is nessesary after first scan?
There is example of WB Code https://www.hascode.com/2010/05/playing-around-with-qr-codes/

**Pull request merged**
