### PR TITLE
Add support for continuous scan

### PR DESCRIPTION
**Pull request by Codewaves**
Possibility to enable continuous scan mode. Scanner will not stop decoding on first successful scan.

### CODE REVIEW

**Comment by yuriy-budiyev** [comment]
Good idea, but I'll change behavior a bit :)

**Comment by Codewaves** [comment]
Sure :)
I need functionality that shows camera preview, but doesn't accept codes until user presses the button.

**Comment by yuriy-budiyev** [comment]
Released in version 1.7.0

**Comment by yuriy-budiyev** [comment]
Check 1.7.1

**Comment by Codewaves** [comment]
Thank you.

**Pull request merged**
